# COVID 19 PROJECT

Sources
- [https://data.covid19india.org/v4/min/data.min.json](https://data.covid19india.org/v4/min/data.min.json)
- [https://data.covid19india.org/v4/min/timeseries.min.json](https://data.covid19india.org/v4/min/timeseries.min.json)

 In order to better understand the data, use the below given resources:
 - https://data.covid19india.org/documentation/v4_data.html
 - https://data.covid19india.org/documentation/timeseries.min.html

modules used

In [4]:
import requests as req
import json
import pandas as pd
import csv

In [5]:
url_data = 'https://data.covid19india.org/v4/min/data.min.json'
url_timeseries = 'https://data.covid19india.org/v4/min/timeseries.min.json'

Variable has been created of url string

##### Requesting Data from URL

In [9]:
r_url_data = req.get(url_data)
r_url_time = req.get(url_timeseries)

#### Parsing Data

collecting the json data direct from url text method has been used

In [7]:
data_json = r_url_data.text
timeseries_json = r_url_time.text

In [17]:
data = json.loads(data_json)
data1 = json.loads(data_json)
timeseries = json.loads(timeseries_json)

In [18]:
for x in data1:
    try:
        
        del data1[x]['districts']
    except:
        pass

we have created the different files for district data and state data that's why we have deleted the district from state table file

In [31]:

timeseries_list = []
for x in timeseries:
    st = x
    for y in timeseries[x]['dates']:
        try:
            timeseries[x]['dates'][y]['state'] = st
            timeseries[x]['dates'][y]['date'] = y
            timeseries_list.append(timeseries[x]['dates'][y])
        except:
            pass

appending the state column in timeseriese file

timeseries list has been created which data for each day

In [44]:
timeseries_final = pd.json_normalize(timeseries_list)
timeseries_final

,state,date,delta.confirmed,delta7.confirmed,total.confirmed,delta.recovered,delta7.recovered,total.recovered,delta.tested,delta7.tested,...,total.other,delta.deceased,delta7.deceased,total.deceased,delta.vaccinated1,delta7.vaccinated1,total.vaccinated1,delta.vaccinated2,delta7.vaccinated2,total.vaccinated2
0,AN,2020-03-26,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AN,2020-03-27,5.0,6.0,6.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AN,2020-03-28,3.0,9.0,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AN,2020-03-29,NaN,9.0,9.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AN,2020-03-30,1.0,10.0,10.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21673,WB,2021-10-27,976.0,6229.0,1589042.0,837.0,5658.0,1561973.0,43322.0,270214.0,...,NaN,15.0,89.0,19096.0,323292.0,4217789.0,53992006.0,229056.0,1852144.0,20590859.0
21674,WB,2021-10-28,990.0,6386.0,1590032.0,845.0,5728.0,1562818.0,45437.0,282633.0,...,NaN,9.0,84.0,19105.0,532317.0,4081493.0,54524323.0,287998.0,1884201.0,20878857.0
21675,WB,2021-10-29,982.0,6522.0,1591014.0,860.0,5796.0,1563678.0,49017.0,291347.0,...,NaN,8.0,80.0,19113.0,701727.0,3980686.0,55226050.0,317576.0,1879824.0,21196433.0
21676,WB,2021-10-30,980.0,6528.0,1591994.0,880.0,5868.0,1564558.0,47131.0,295319.0,...,NaN,13.0,81.0,19126.0,756507.0,3809335.0,55982557.0,304433.0,1870225.0,21500866.0
21677,WB,2021-10-31,914.0,6453.0,1592908.0,913.0,5953.0,1565471.0,47417.0,300114.0,...,NaN,15.0,86.0,19141.0,209609.0,3809597.0,56192166.0,58881.0,1871612.0,21559747.0

In [21]:
data_list =  [x for x in data1.values()]
state_list = [ x for x in data1]
for x in range(len(data_list)):
    data_list[x]['state'] = state_list[x]

In [22]:
state_data = pd.json_normalize(data_list)   #without districts

In [43]:
state_data

,state,delta.tested,delta.vaccinated1,delta.vaccinated2,delta21_14.confirmed,delta7.confirmed,delta7.recovered,delta7.tested,delta7.vaccinated1,delta7.vaccinated2,...,total.vaccinated2,delta.confirmed,delta.deceased,delta.recovered,delta7.deceased,meta.notes,total.other,delta7.other,delta.other,meta.vaccinated.source
0,AN,1376.0,3.0,13.0,9.0,3.0,5.0,8936.0,884,10640,...,200157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AP,39848.0,20497.0,24137.0,3220.0,2873.0,3590.0,254532.0,1223010,1887005,...,20375181,385.0,4.0,675.0,30.0,NaN,NaN,NaN,NaN,NaN
2,AR,334.0,42.0,195.0,87.0,66.0,97.0,4788.0,3312,23647,...,534486,1.0,NaN,9.0,NaN,[July 25]: All numbers corresponding to Papum ...,NaN,NaN,NaN,NaN
3,AS,15060.0,19124.0,37463.0,1499.0,2056.0,2215.0,269097.0,274869,849889,...,8068795,212.0,1.0,236.0,24.0,[Jan 1]: 1347 cases i.e Covid +'tive patients ...,1347.0,NaN,NaN,NaN
4,BR,226443.0,114694.0,145827.0,30.0,40.0,31.0,1378539.0,1286708,2144970,...,18346781,8.0,NaN,9.0,NaN,[June 9] : 3951 deceased cases have been repor...,1.0,NaN,NaN,NaN
5,CH,1403.0,211.0,1282.0,23.0,28.0,20.0,10726.0,3680,21641,...,546981,5.0,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
6,CT,11869.0,21312.0,39393.0,124.0,205.0,103.0,147451.0,379374,604260,...,7343273,32.0,1.0,32.0,5.0,NaN,NaN,NaN,NaN,NaN
7,DL,56751.0,12482.0,11839.0,195.0,267.0,239.0,395086.0,160323,269146,...,7425404,45.0,NaN,46.0,NaN,[July 14]: Value for the total tests conducted...,NaN,NaN,NaN,NaN
8,DN,NaN,3.0,20.0,4.0,NaN,2.0,NaN,2802,14244,...,370255,NaN,NaN,1.0,NaN,NaN,31.0,NaN,NaN,NaN
9,GA,2361.0,2572.0,12404.0,409.0,222.0,409.0,19026.0,8418,46494,...,911114,23.0,NaN,53.0,6.0,NaN,NaN,NaN,NaN,NaN
10,GJ,34282.0,14685.0,62096.0,149.0,159.0,116.0,328489.0,335172,1660382,...,25972387,20.0,NaN,23.0,2.0,NaN,NaN,NaN,NaN,NaN
11,HP,3613.0,371.0,8192.0,958.0,1537.0,1154.0,64352.0,13244,234011,...,3443823,85.0,1.0,198.0,20.0,NaN,16.0,-1.0,NaN,NaN
12,HR,20588.0,7867.0,15801.0,83.0,95.0,87.0,148110.0,160777,368141,...,8115463,11.0,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
13,JH,31238.0,41034.0,51488.0,78.0,137.0,250.0,464579.0,299587,428313,...,5585648,10.0,NaN,8.0,3.0,NaN,NaN,NaN,NaN,NaN
14,JK,38915.0,1584.0,45202.0,529.0,611.0,572.0,254608.0,33383,414843,...,5149471,95.0,NaN,79.0,3.0,NaN,NaN,NaN,NaN,NaN
15,KA,106939.0,17604.0,28163.0,2432.0,2347.0,2339.0,724215.0,623591,1373861,...,22858384,292.0,11.0,345.0,75.0,NaN,29.0,NaN,NaN,NaN
16,KL,65158.0,2010.0,11914.0,59521.0,53326.0,48406.0,506604.0,109805,792534,...,13658343,7167.0,167.0,6439.0,3089.0,NaN,529.0,NaN,NaN,NaN
17,LA,388.0,NaN,2.0,26.0,58.0,28.0,2475.0,525,1532,...,152280,11.0,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN
18,LD,31.0,NaN,4.0,NaN,NaN,NaN,1625.0,69,796,...,45951,NaN,NaN,NaN,NaN,NaN,44.0,NaN,NaN,NaN
19,MH,108040.0,53161.0,31988.0,13825.0,8117.0,15146.0,773516.0,1611778,1282938,...,30975692,1172.0,20.0,1399.0,200.0,"[Dec 16]:10,218 duplicate cases & other state ...",3619.0,7.0,NaN,NaN
20,ML,1559.0,38.0,203.0,530.0,256.0,460.0,13944.0,7871,41927,...,641819,22.0,1.0,51.0,4.0,NaN,NaN,NaN,NaN,NaN
21,MN,1689.0,705.0,4283.0,734.0,439.0,652.0,12787.0,7665,71276,...,719413,63.0,1.0,62.0,10.0,[Dec 14]:824 out of 980 recovered cases are ba...,NaN,NaN,NaN,NaN
22,MP,55368.0,5713.0,77062.0,63.0,105.0,74.0,393209.0,148817,2034460,...,20838045,16.0,NaN,8.0,1.0,[14 Oct'20]: 4469 confirmed cases and 4469 rec...,NaN,NaN,NaN,NaN
23,MZ,5945.0,10.0,51.0,6770.0,4098.0,5685.0,42841.0,4302,11262,...,512029,579.0,2.0,610.0,21.0,NaN,NaN,NaN,NaN,NaN
24,NL,468.0,193.0,822.0,162.0,130.0,144.0,4606.0,4706,23628,...,490663,11.0,1.0,21.0,6.0,NaN,1043.0,13.0,1.0,NaN
25,OR,69675.0,21420.0,25651.0,3381.0,3046.0,3230.0,473919.0,731837,917236,...,11560912,488.0,4.0,450.0,24.0,[July 12th] :20 non-covid deaths reported in s...,NaN,NaN,NaN,NaN
26,PB,34152.0,3321.0,4418.0,159.0,192.0,162.0,221114.0,200182,223256,...,6238973,26.0,1.0,25.0,8.0,NaN,NaN,NaN,NaN,NaN
27,PY,2662.0,171.0,532.0,343.0,278.0,315.0,21095.0,8324,20073,...,404355,38.0,NaN,45.0,NaN,NaN,NaN,NaN,NaN,NaN
28,RJ,13454.0,9399.0,29672.0,31.0,27.0,26.0,95132.0,271500,864947,...,20097635,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
29,SK,389.0,NaN,NaN,82.0,79.0,76.0,2847.0,782,14044,...,451509,21.0,1.0,8.0,2.0,NaN,325.0,6.0,NaN,NaN
30,TG,25021.0,38781.0,26738.0,1068.0,1189.0,1121.0,261086.0,1072389,961422,...,9772398,121.0,1.0,183.0,9.0,[July 27] : Telangana bulletin for the previou...,NaN,NaN,NaN,NaN
31,TN,123701.0,77325.0,106584.0,8827.0,7407.0,8852.0,858304.0,788134,1578082,...,17619141,1009.0,19.0,1183.0,97.0,[June 29 2021]: TN has introduced a new distri...,NaN,NaN,NaN,NaN
32,TR,3501.0,3.0,650.0,49.0,87.0,62.0,22126.0,4155,74642,...,1621329,12.0,NaN,2.0,NaN,[Aug 4]: Tripura bulletin for the previous day...,63.0,NaN,NaN,NaN
33,TT,881379.0,750410.0,933460.0,109755.0,96071.0,101753.0,8431577.0,15883780,24527530,...,330752697,12907.0,251.0,13152.0,3727.0,NaN,13197.0,37.0,1.0,https://www.pib.gov.in/PressReleasePage.aspx?P...
34,UP,161458.0,53401.0,57556.0,74.0,63.0,58.0,1140736.0,2266921,3130828,...,32681895,6.0,NaN,6.0,1.0,[Jan 1]:As no bulletin was provided for 31'st ...,NaN,NaN,NaN,NaN
35,UT,9524.0,1065.0,12934.0,88.0,75.0,74.0,83377.0,25250,258381,...,3898342,5.0,NaN,9.0,1.0,[Oct 30]: Metric of capturing the testing data...,6150.0,12.0,NaN,NaN
36,WB,47417.0,209609.0,58881.0,4193.0,6453.0,5953.0,300114.0,3809597,1871612,...,21559747,914.0,15.0,913.0,86.0,NaN,NaN,NaN,NaN,NaN

In [24]:
data_list_1 =  [x for x in data.values()]
state_list_1 = [ x for x in data]
for x in range(len(data_list)):
    try:
        data_list_1[x]['districts']['state'] = state_list[x] 
    except:
        pass

In [25]:
district_data = []
for x in data_list_1:
    try:
        district_data.append(x['districts'])
    except:
        pass

In [26]:
for x in district_data:
    st = x['state']
    for y in x:
        try:
            x[y]['state'] = st
            x[y]['district'] = y
        except:
            pass

In [27]:
district_data_1 = []
for x in district_data:
    for y in x:
        if y == 'state':
            continue
        
        district_data_1.append(x[y])

In [28]:
district_data_final = pd.json_normalize(district_data_1)

In [30]:
district_data_final

,state,district,delta7.vaccinated1,delta7.vaccinated2,meta.population,total.vaccinated1,total.vaccinated2,delta.vaccinated2,delta.vaccinated1,delta21_14.confirmed,...,delta.deceased,delta7.deceased,total.other,delta.tested,delta7.tested,meta.tested.source,meta.vaccinated.date,delta7.other,meta.notes,delta.other
0,AN,Nicobars,62.0,811.0,36842.0,25394.0,20313.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AN,North and Middle Andaman,90.0,1839.0,105597.0,78945.0,59522.0,8.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AN,South Andaman,732.0,8012.0,238142.0,189662.0,120322.0,28.0,3.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AP,Anantapur,92803.0,140903.0,4083315.0,2690082.0,1611476.0,5370.0,4575.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
743,WB,Purba Bardhaman,260764.0,51741.0,4835532.0,2596246.0,859528.0,4002.0,17168.0,132.0,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744,WB,Purba Medinipur,71724.0,144185.0,4417377.0,3560589.0,1471674.0,2226.0,5370.0,65.0,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
745,WB,Purulia,159111.0,40922.0,2927965.0,1679941.0,492310.0,1866.0,13266.0,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
746,WB,South 24 Parganas,310444.0,169231.0,8153176.0,4850898.0,1832073.0,3270.0,7086.0,267.0,...,1.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
747,WB,Uttar Dinajpur,130243.0,44686.0,3000849.0,1341457.0,436182.0,NaN,NaN,25.0,...,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
district_data_final.to_csv('dsitrict_data.csv')
timeseries_final.to_csv('timeseries_data.csv')
state_data.to_csv('state_data.csv')

saving the files into csv